// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function logMe(x) {
  console.log(x);
  return x;
}

function intAdd(x, y) {
  return x + y | 0;
}

exports.logMe = logMe;
exports.intAdd = intAdd;
/* No side effect */
